# Generated by Django 4.2.8 on 2023-12-22 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.userprofile'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_customers', to='register.userprofile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
